startuml
namespace dto {
    class "AccessTokenRequestData" << (S,Aquamarine) >> {
        + ClientId string
        + ClientSecret string

    }
    class "AppInstanceNodeMigrateRequest" << (S,Aquamarine) >> {
        + NsId string
        + VnfId string
        + KduId string
        + Node string

    }
    class "AppiDetails" << (S,Aquamarine) >> {
        + Domain string
        + Instances <font color=blue>map</font>[string]Instance

    }
    class "ArtefactOnboardRequest" << (S,Aquamarine) >> {
        + ArtefactId string
        + ArtefactName string
        + AppProviderId string
        + ArtefactVersionInfo string
        + ArtefactVirtType models.ArtefactVirtType
        + ArtefactDescriptorType models.ArtefactDescriptorType
        + ComponentSpec []models.ComponentSpec
        + ArtefactDescription string
        + ArtefactFileName string
        + ArtefactFileFormat models.ArtefactFileFormat
        + RepoType models.RepoType
        + ArtefactRepoLocation models.ObjectRepoLocation

        + Validate() error

    }
    class "Cluster" << (S,Aquamarine) >> {
        + Domain string
        + Name string
        + K8sVersion string
        + VIMAccount string
        + Description string
        + Nets Net
        + NodeSpecs <font color=blue>map</font>[string]NodeSpec

    }
    class "DeleteAppPkgMessage" << (S,Aquamarine) >> {
        + AppPkgId string

    }
    class "DisableAppInstanceKDUMessage" << (S,Aquamarine) >> {
        + AppdId string
        + KDUId string
        + NSId string

    }
    class "DisableAppInstanceKDURequest" << (S,Aquamarine) >> {
        + NsId string
        + KduId string

    }
    class "EnableAppInstanceKDUMessage" << (S,Aquamarine) >> {
        + AppdId string
        + KDUId string
        + NSId string
        + Node string

    }
    class "EnableAppInstanceKDURequest" << (S,Aquamarine) >> {
        + KduId string
        + NsId string
        + Node string

    }
    class "FederatedAppisMessage" << (S,Aquamarine) >> {
        + Appis <font color=blue>map</font>[string]AppiDetails

    }
    class "FederationInitiateRequestData" << (S,Aquamarine) >> {
        + FederationEndpoint string
        + AuthEndpoint string

    }
    class "FederationRenewalResponseData" << (S,Aquamarine) >> {
        + FederationContextId string
        + FederationExpiryDate time.Time
        + FederationRenewalDate time.Time

    }
    class "GetArtefactResponse" << (S,Aquamarine) >> {
        + ArtefactId string
        + AppProviderId string
        + ArtefactVersionInfo string
        + ArtefactName string
        + ArtefactDescription string
        + ArtefactVirtType models.ArtefactVirtType
        + ArtefactDescriptorType models.ArtefactDescriptorType
        + ArtefactRepoLocation models.ObjectRepoLocation
        + ArtefactFileFormat models.ArtefactFileFormat

    }
    class "InfrastructureInfo" << (S,Aquamarine) >> {
        + MsgID string
        + Clusters <font color=blue>map</font>[string]Cluster

        + UnmarshalJSON(data []byte) error

    }
    class "Instance" << (S,Aquamarine) >> {
        + NSID string
        + VNFID string
        + KDUs <font color=blue>map</font>[string]string

    }
    class "InstantiateAppPkgMessage" << (S,Aquamarine) >> {
        + AppPkgId string
        + Name string
        + Description string
        + VimId string
        + Config string
        + OriginDomain string

    }
    class "InstantiateApplicationRequest" << (S,Aquamarine) >> {
        + TransactionId string
        + AppId string
        + AppProviderId string
        + AppVersion string
        + ZoneInfo string
        + AppInstCallbackLink string
        + Config string

    }
    class "MigrateAppInstanceNodeMessage" << (S,Aquamarine) >> {
        + AppdId string
        + NsId string
        + VnfId string
        + KduId string
        + Node string

    }
    class "NewAppInstanceMessage" << (S,Aquamarine) >> {
        + AppInstanceId string

    }
    class "NewAppPkg" << (S,Aquamarine) >> {
        + AppdId string
        + Name string
        + Provider string
        + Version string
        + MecVersion string
        + InfoName string
        + Description string
        + AppD []byte

    }
    class "NewAppPkgMessage" << (S,Aquamarine) >> {
        + AppPkgId string

    }
    class "NodeSpec" << (S,Aquamarine) >> {
        + NumCPUCores int
        + MemorySize float64
        + AllocatedCPU int
        + AllocatedMem int

    }
    class "OnboardApplicationRequest" << (S,Aquamarine) >> {
        + AppId string
        + AppName string
        + ArtefactId string

    }
    class "OrchAppI" << (S,Aquamarine) >> {
        + AppiId string
        + Domain string
        + Instances <font color=blue>map</font>[string]<font color=blue>map</font>[string]Instance
        + AppPkgId string
        + NsPkgId string
        + VnfPkgId string

    }
    class "OrchAppPkg" << (S,Aquamarine) >> {
        + Id bson.ObjectID
        + AppdId string
        + Name string
        + Provider string
        + Version string
        + MecVersion string
        + InfoName string
        + Description string
        + AppD []byte
        + NsPkgId string
        + VnfPkgId string

    }
    class "OrchMehMetricsRequestData" << (S,Aquamarine) >> {
        + Metrics <font color=blue>map</font>[string]any

    }
    class "TerminateAppiMessage" << (S,Aquamarine) >> {
        + AppiId string

    }
    class "dto.Net" << (T, #FF7700) >>  {
    }
}
namespace models {
    class "AccessToken" << (S,Aquamarine) >> {
        + ClientId string
        + AccessToken string
        + ExpiresAt time.Time

    }
    class "AffectedService" << (S,Aquamarine) >> {
        + AffectedService []string

    }
    class "AlarmDetails" << (S,Aquamarine) >> {
        + AlarmDetails string

    }
    class "AlarmIdentifier" << (S,Aquamarine) >> {
        + AlarmId string

    }
    class "AlarmObjectInfo" << (S,Aquamarine) >> {
        + AlarmType *AlarmType
        + AlarmId *AlarmIdentifier
        + PerceivedSeverity *PerceivedSeverity
        + ProbableCause *ProbableCause
        + AlarmedObject *AlarmedObject
        + SourceSystemId *SourceSystemId
        + State *State
        + AlarmRaisedTime *AlarmRaisedTime
        + AffectedService *AffectedService
        + AlarmDetails *AlarmDetails
        + SpecificProblem *SpecificProblem
        + ServiceAffecting *ServiceAffecting

    }
    class "AlarmRaisedTime" << (S,Aquamarine) >> {
        + AlarmRaisedTime time.Time

    }
    class "AlarmType" << (S,Aquamarine) >> {
        + AlarmType string

    }
    class "AlarmedObject" << (S,Aquamarine) >> {
        + AlarmId *AlarmIdentifier
        + Href string

    }
    class "AnyOfAppComponentsItems" << (S,Aquamarine) >> {
    }
    class "AnyOfServiceEndpoint" << (S,Aquamarine) >> {
    }
    class "AppAggrResUtil" << (S,Aquamarine) >> {
        + AppId string
        + AppProvId string
        + NoOfAppInstances int32
        + AppInstances []string
        + CpuUtil *CpuUtilization
        + MemUtil *MemUtilization
        + DiskUtil *DiskUtilization
        + NetworkUtil *NetworkUtilization
        + FlavourUtil *[]FlavourMetrics

    }
    class "AppInstInfo" << (S,Aquamarine) >> {
        + AppInstState AppInstState
        + AccessPointInfo []string

    }
    class "AppInstNetworkCapList" << (S,Aquamarine) >> {
        + AppInstanceNwCapInfo []<font color=blue>interface</font>{}

    }
    class "AppInstance" << (S,Aquamarine) >> {
        + Id string
        + FederationContextId string
        + Name string
        + Description string
        + AppId string
        + AppiId string
        + NsId string
        + VnfId string

    }
    class "AppMetaData" << (S,Aquamarine) >> {
        + AppName string
        + Version string
        + AppDescription string
        + MobilitySupport bool
        + AccessToken string
        + Category string

    }
    class "AppQoSProfile" << (S,Aquamarine) >> {
        + LatencyConstraints *LatencyConstraints
        + BandwidthRequired int32
        + MultiUserClients *MultiUserClients
        + NoOfUsersPerAppInst int32
        + AppProvisioning bool

    }
    class "Application" << (S,Aquamarine) >> {
        + Id string
        + FederationContextId string
        + Name string
        + Description string
        + ArtefactId string
        + AppPkgId string

    }
    class "AppsResUtilizeInfo" << (S,Aquamarine) >> {
        + AppMetrics []AppsResUtilizeMetrics
        + FederationContextId string
        + SequenceNum int32

    }
    class "AppsResUtilizeMetrics" << (S,Aquamarine) >> {
        + ZoneId string
        + StartTime *time.Time
        + EndTime *time.Time
        + AppZoneMetrics *[]AppAggrResUtil

    }
    class "Artefact" << (S,Aquamarine) >> {
        + Id string
        + FederationContextId string
        + AppProviderId string
        + Name string
        + VersionInfo string
        + Description string
        + VirtType ArtefactVirtType
        + DescriptorType ArtefactDescriptorType
        + FileName string
        + FileFormat ArtefactFileFormat
        + ArtefactFile *[]byte
        + ComponentSpec []ComponentSpec
        + ObjectRepoLocation ObjectRepoLocation
        + AppPkgId string

    }
    class "ClientLocation" << (S,Aquamarine) >> {
        + GeoLocation string
        + RadLocation []<font color=blue>interface</font>{}

    }
    class "CommandLineParams" << (S,Aquamarine) >> {
        + Command []string
        + CommandArgs []string

    }
    class "CompEnvParams" << (S,Aquamarine) >> {
        + EnvVarName string
        + EnvValueType string
        + EnvVarValue string
        + EnvVarSrc string

    }
    class "ComponentSpec" << (S,Aquamarine) >> {
        + ComponentName string
        + Images []string
        + NumOfInstances int32
        + RestartPolicy string
        + CommandLineParams *CommandLineParams
        + ExposedInterfaces []InterfaceDetails
        + ComputeResourceProfile *ComputeResourceInfo
        + CompEnvParams []CompEnvParams
        + DeploymentConfig *DeploymentConfig
        + PersistentVolumes []PersistentVolumeDetails

    }
    class "ComputeResourceInfo" << (S,Aquamarine) >> {
        + CpuArchType string
        + NumCPU string
        + Memory int64
        + DiskStorage int32
        + Gpu []GpuInfo
        + Vpu int32
        + Fpga int32
        + Hugepages []HugePage
        + CpuExclusivity bool

    }
    class "CpuUtilization" << (S,Aquamarine) >> {
        + CpuType *MonitoringSubsType
        + NoOfSamples string
        + AverageUtilization *UtilizationValue
        + MaxUtilization *UtilizationValue
        + MinUtilization *UtilizationValue
        + EffectiveUtilization *UtilizationValue

    }
    class "DeploymentConfig" << (S,Aquamarine) >> {
        + ConfigType string
        + Contents string

    }
    class "DetectedEvent" << (S,Aquamarine) >> {
        + ZoneId string
        + EventId string
        + StartTime *time.Time
        + EndTime *time.Time
        + NumOccurance int32

    }
    class "DeviceConnStatusChangeCap" << (S,Aquamarine) >> {
        + CapabilityId *CapabilityId
        + MaxiDetectionTime string

    }
    class "DiskUtilization" << (S,Aquamarine) >> {
        + NoOfSamples string
        + AverageUtilization *UtilizationValue
        + MaxUtilization *UtilizationValue
        + MinUtilization *UtilizationValue
        + EffectiveUtilization *UtilizationValue

    }
    class "DynamicQoSCap" << (S,Aquamarine) >> {
        + CapabilityId *CapabilityId
        + SupportedQoS string

    }
    class "EdgeComputeMetrics" << (S,Aquamarine) >> {
        + ZoneId string
        + StartTime *time.Time
        + EndTime *time.Time
        + CpuUtil *CpuUtilization
        + MemUtil *MemUtilization
        + DiskUtil *DiskUtilization
        + NetworkUtil *NetworkUtilization
        + FlavourUtil *[]FlavourMetrics

    }
    class "EdgeResUtilizeMetrics" << (S,Aquamarine) >> {
        + EdgeMetrics []EdgeComputeMetrics
        + FederationContextId string
        + SequenceNum int32

    }
    class "EventCriterion" << (S,Aquamarine) >> {
        + ResUsageType *ResourceType
        + TriggerCondition string
        + ThresholdVal *ThresholdVal
        + NumOccurance int32
        + MonitorDuration *PeriodicityInterval

    }
    class "EventInfo" << (S,Aquamarine) >> {
        + EventId string
        + EventCriterion *EventCriterion

    }
    class "EventSubscription" << (S,Aquamarine) >> {
        + ResUsageType *ResourceType
        + Periodicity *PeriodicityInterval
        + EventListner string

    }
    class "EventSubscriptionInfo" << (S,Aquamarine) >> {
        + ResUsageType *ResourceType
        + Periodicity *PeriodicityInterval
        + SubscriptionId string

    }
    class "ExpiryInterval" << (S,Aquamarine) >> {
        + NumHours int32
        + NumMins int32
        + NumSecs int32

    }
    class "Federation" << (S,Aquamarine) >> {
        + OriginOP FederationRequestData
        + PartnerOP FederationResponseData
        + HealthInfo FederationHealthInfo
        + FederationEndpoint string
        + AuthEndpoint string
        + IsEstablished bool
        + IsOriginOP bool

    }
    class "FederationApiResources" << (S,Aquamarine) >> {
        + Name *FederationApiNames
        + ApiOperations []HttpResources

    }
    class "FederationHealthInfo" << (S,Aquamarine) >> {
        + FederationStatus *State
        + FederationStartTime time.Time
        + NumOfAcceptedZones string
        + NumOfActiveAlarms string
        + NumOfApplications string

    }
    class "FederationMetaInfo" << (S,Aquamarine) >> {
        + EdgeDiscoveryServiceEndPoint *ServiceEndpoint
        + OfferedAvailabilityZones []ZoneDetails
        + AllowedMobileNetworkIds *MobileNetworkIds
        + AllowedFixedNetworkIds *[]string
        + LcmServiceEndPoint *ServiceEndpoint
        + PlatformCaps *[]string

    }
    class "FederationPatchParams" << (S,Aquamarine) >> {
        + ObjectType string
        + OperationType string
        + ModificationDate string
        + AddMobileNetworkIds *MobileNetworkIds
        + RemoveMobileNetworkIds *MobileNetworkIds
        + AddFixedNetworkIds *[]string
        + RemoveFixedNetworkIds *[]string

    }
    class "FederationRequestData" << (S,Aquamarine) >> {
        + OrigOPFederationId string
        + OrigOPCountryCode string
        + OrigOPMobileNetworkCodes *MobileNetworkIds
        + OrigOPFixedNetworkCodes *[]string
        + InitialDate time.Time
        + PartnerStatusLink string
        + AccessToken AccessToken

    }
    class "FederationResponseData" << (S,Aquamarine) >> {
        + PartnerOPFederationId string
        + PartnerOPCountryCode string
        + FederationContextId string
        + EdgeDiscoveryServiceEndPoint *ServiceEndpoint
        + LcmServiceEndPoint *ServiceEndpoint
        + PartnerOPMobileNetworkCodes *MobileNetworkIds
        + PartnerOPFixedNetworkCodes *[]string
        + OfferedAvailabilityZones []ZoneDetails
        + PlatformCaps *[]string
        + FederationExpiryDate time.Time
        + FederationRenewalDate time.Time

    }
    class "FederationSupportedApis" << (S,Aquamarine) >> {
        + FederationBaseAPI *FederationApiResources
        + AvailabilityZoneAPI *FederationApiResources
        + EdgeApplicationAPI *FederationApiResources
        + ArtefactAPI *FederationApiResources
        + FileAPI *FederationApiResources
        + ServiceAPIFederation *FederationApiResources
        + ResourceMonitoringAPI *FederationApiResources
        + FaultManagementAPI *FederationApiResources
        + EventManagementAPI *FederationApiResources

    }
    class "File" << (S,Aquamarine) >> {
        + Id string
        + FederationContextId string
        + FileName string
        + FileDescription string
        + FileVersionInfo string
        + FileType VirtImageType
        + Checksum string
        + ImgOsType OsType
        + ImgInsSetArch CpuArchType
        + RepoType RepoType
        + ObjectRepoLocation ObjectRepoLocation
        + ArtefactFile *[]byte

    }
    class "Flavour" << (S,Aquamarine) >> {
        + FlavourId string
        + CpuArchType *CpuArchType
        + SupportedOSTypes []OsType
        + NumCPU int32
        + MemorySize int32
        + StorageSize int32
        + Gpu []GpuInfo
        + Fpga int32
        + Vpu int32
        + Hugepages []HugePage
        + CpuExclusivity bool

    }
    class "FlavourMetrics" << (S,Aquamarine) >> {
        + NoOfSamples string
        + FlavourId string
        + AverageUtilization *UtilizationValue
        + AverageThroughput *UtilizationValue
        + MaxUtilization *UtilizationValue
        + MinUtilization *UtilizationValue

    }
    class "GpuInfo" << (S,Aquamarine) >> {
        + GpuVendorType string
        + GpuModeName string
        + GpuMemory int32
        + NumGPU int32

    }
    class "HttpResources" << (S,Aquamarine) >> {
        + Href string
        + HttpMethods []HttpMethods

    }
    class "HugePage" << (S,Aquamarine) >> {
        + PageSize string
        + Number int32

    }
    class "InterfaceDetails" << (S,Aquamarine) >> {
        + InterfaceId string
        + CommProtocol string
        + CommPort int32
        + VisibilityType string
        + Network string
        + InterfaceName string

    }
    class "InvalidParam" << (S,Aquamarine) >> {
        + Param string
        + Reason string

    }
    class "LocationRetrievalCap" << (S,Aquamarine) >> {
        + CapabilityId *CapabilityId
        + LocationType string
        + LocationAccuracy string

    }
    class "MemUtilization" << (S,Aquamarine) >> {
        + NoOfSamples string
        + AverageUtilization *UtilizationValue
        + MaxUtilization *UtilizationValue
        + MinUtilization *UtilizationValue
        + EffectiveUtilization *UtilizationValue

    }
    class "MobileNetworkIds" << (S,Aquamarine) >> {
        + Mcc string
        + Mncs []string

    }
    class "NetworkCapInvoked" << (S,Aquamarine) >> {
        + NetworkEventId string
        + CapabilityId *CapabilityId
        + InvocationTime *time.Time
        + NwCapabilitySLI string
        + ZoneId string

    }
    class "NetworkCapSubsInfo" << (S,Aquamarine) >> {
        + AppId string
        + AppProviderId string
        + CapabilityId *CapabilityId

    }
    class "NetworkUtilization" << (S,Aquamarine) >> {
        + NoOfSamples string
        + IngressUsage *UtilizationValue
        + EgressUsage *UtilizationValue
        + AverageThroughput *UtilizationValue
        + MaxThroughput *UtilizationValue
        + MinThroughput *UtilizationValue

    }
    class "NodeDiscoveryResponse" << (S,Aquamarine) >> {
        + EdgeNodes *[]<font color=blue>interface</font>{}
        + DiscoveredAppInsts *[]<font color=blue>interface</font>{}

    }
    class "ObjectRepoLocation" << (S,Aquamarine) >> {
        + RepoURL string
        + UserName string
        + Password string
        + Token string

    }
    class "OrchestratorInfo" << (S,Aquamarine) >> {
        + OperatorId string
        + OperatorName string
        + OperatorCountryCode string
        + MobileCountryCode string
        + MobileNetworkCodes []string
        + KafkaUrl string

    }
    class "OsType" << (S,Aquamarine) >> {
        + Architecture string
        + Distribution string
        + Version string
        + License string

    }
    class "PerceivedSeverity" << (S,Aquamarine) >> {
        + Severity string

    }
    class "PeriodicNotifConfig" << (S,Aquamarine) >> {
        + Periodicity *PeriodicityInterval
        + NotificationListner string

    }
    class "PeriodicityInterval" << (S,Aquamarine) >> {
        + NumHours int32
        + NumMins int32

    }
    class "PersistentVolumeDetails" << (S,Aquamarine) >> {
        + VolumeSize string
        + VolumeMountPath string
        + VolumeName string
        + EphemeralType bool
        + AccessMode string
        + SharingPolicy string

    }
    class "ProbableCause" << (S,Aquamarine) >> {
        + Cause string

    }
    class "ProblemDetails" << (S,Aquamarine) >> {
        + Title string
        + Detail string
        + Cause string
        + InvalidParams []InvalidParam

    }
    class "ResourceReservationDuration" << (S,Aquamarine) >> {
        + NumOfDays int32
        + NumOfMonths int32
        + NumOfYears int32

    }
    class "ResourceSubscriptionInfo" << (S,Aquamarine) >> {
        + MonitoringType *MonitoringSubsType
        + DateAndTime *time.Time
        + SubscriptionId string

    }
    class "ServiceApiContent" << (S,Aquamarine) >> {
        + MediaType *ApiContentType

    }
    class "ServiceApiEventDef" << (S,Aquamarine) >> {
    }
    class "ServiceApiNetworkEvent" << (S,Aquamarine) >> {
        + ConnectID string
        + CustomerID string
        + EventType *SvcEventType
        + ServiceAPIEventDef *ServiceApiEventDef
        + ExpiryDuration *ExpiryInterval

    }
    class "ServiceApiResponse" << (S,Aquamarine) >> {
        + CustomerID string
        + TargetUserContext *TargetUserContext
        + ApiResponse string
        + TxnIdentifier string

    }
    class "ServiceEndpoint" << (S,Aquamarine) >> {
        + Port int32
        + Fqdn string
        + Ipv4Addresses []string
        + Ipv6Addresses []string

    }
    class "SourceSystemId" << (S,Aquamarine) >> {
        + SourceSystemId string

    }
    class "SpecificProblem" << (S,Aquamarine) >> {
        + SpecificProblem string

    }
    class "State" << (S,Aquamarine) >> {
        + AlarmState string

    }
    class "SubscriptionIdentifier" << (S,Aquamarine) >> {
        + SubsId string

    }
    class "TargetUserContext" << (S,Aquamarine) >> {
        + ConnectID string
        + ExpiryDuration *ExpiryInterval

    }
    class "ThresholdVal" << (S,Aquamarine) >> {
        + Value string
        + Unit string

    }
    class "UpdatedAlarmParameters" << (S,Aquamarine) >> {
        + AlarmId *AlarmIdentifier
        + UpdateParams []UpdatedParam

    }
    class "UpdatedParam" << (S,Aquamarine) >> {
        + AlarmUpdateOps *AlarmUpdateOps
        + PatchableParam *PatchableParams
        + PatchValue string

    }
    class "UserPlaneMgmtEvtCap" << (S,Aquamarine) >> {
        + CapabilityId *CapabilityId
        + MaxUserPlaneLatency string

    }
    class "UtilizationValue" << (S,Aquamarine) >> {
        + ResType *ResourceType
        + Value string
        + Unit string

    }
    class "ZoneDetails" << (S,Aquamarine) >> {
        + ZoneId string
        + VimId string
        + Geolocation string
        + GeographyDetails string

    }
    class "ZoneRegisteredData" << (S,Aquamarine) >> {
        + ZoneId string
        + FederationContextId string
        + ReservedComputeResources []ComputeResourceInfo
        + ComputeResourceQuotaLimits []ComputeResourceInfo
        + FlavoursSupported []Flavour
        + NetworkResources *<font color=blue>interface</font>{}
        + ZoneServiceLevelObjsInfo *<font color=blue>interface</font>{}

    }
    class "ZoneRegistrationRequestData" << (S,Aquamarine) >> {
        + AcceptedAvailabilityZones []string
        + AvailZoneNotifLink string

    }
    class "ZoneRegistrationResponseData" << (S,Aquamarine) >> {
        + AcceptedZoneResourceInfo []ZoneRegisteredData

    }
    class "models.AlarmUpdateOps" << (T, #FF7700) >>  {
    }
    class "models.ApiContentType" << (T, #FF7700) >>  {
    }
    class "models.AppInstState" << (T, #FF7700) >>  {
    }
    class "models.ArtefactDescriptorType" << (T, #FF7700) >>  {
    }
    class "models.ArtefactFileFormat" << (T, #FF7700) >>  {
    }
    class "models.ArtefactVirtType" << (T, #FF7700) >>  {
    }
    class "models.CapabilityId" << (T, #FF7700) >>  {
    }
    class "models.CpuArchType" << (T, #FF7700) >>  {
    }
    class "models.FederationApiNames" << (T, #FF7700) >>  {
    }
    class "models.HttpMethods" << (T, #FF7700) >>  {
    }
    class "models.LatencyConstraints" << (T, #FF7700) >>  {
    }
    class "models.MonitoringSubsType" << (T, #FF7700) >>  {
    }
    class "models.MultiUserClients" << (T, #FF7700) >>  {
    }
    class "models.OnboardStatusInfo" << (T, #FF7700) >>  {
    }
    class "models.PatchableParams" << (T, #FF7700) >>  {
    }
    class "models.RepoType" << (T, #FF7700) >>  {
    }
    class "models.ResourceType" << (T, #FF7700) >>  {
    }
    class "models.ServiceAffecting" << (T, #FF7700) >>  {
    }
    class "models.ServiceApiNameVal" << (T, #FF7700) >>  {
    }
    class "models.ServiceType" << (T, #FF7700) >>  {
    }
    class "models.Status" << (T, #FF7700) >>  {
    }
    class "models.SvcEventType" << (T, #FF7700) >>  {
    }
    class "models.VirtImageType" << (T, #FF7700) >>  {
    }
}
"__builtin__.<font color=blue>map</font>[string]string" #.. "dto.Net"
"__builtin__.string" #.. "models.AlarmUpdateOps"
"__builtin__.string" #.. "models.ApiContentType"
"__builtin__.string" #.. "models.AppInstState"
"__builtin__.string" #.. "models.ArtefactDescriptorType"
"__builtin__.string" #.. "models.ArtefactFileFormat"
"__builtin__.string" #.. "models.ArtefactVirtType"
"__builtin__.string" #.. "models.CapabilityId"
"__builtin__.string" #.. "models.CpuArchType"
"__builtin__.string" #.. "models.FederationApiNames"
"__builtin__.string" #.. "models.HttpMethods"
"__builtin__.string" #.. "models.LatencyConstraints"
"__builtin__.string" #.. "models.MonitoringSubsType"
"__builtin__.string" #.. "models.MultiUserClients"
"__builtin__.string" #.. "models.OnboardStatusInfo"
"__builtin__.string" #.. "models.PatchableParams"
"__builtin__.string" #.. "models.RepoType"
"__builtin__.string" #.. "models.ResourceType"
"__builtin__.string" #.. "models.ServiceAffecting"
"__builtin__.string" #.. "models.ServiceApiNameVal"
"__builtin__.string" #.. "models.ServiceType"
"__builtin__.string" #.. "models.Status"
"__builtin__.string" #.. "models.SvcEventType"
"__builtin__.string" #.. "models.VirtImageType"



@enduml
