apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mec-federator.secretName" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: federator
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  mongo-username: {{ include "mec-federator.base64" .Values.mongo.username }}
  mongo-password: {{ include "mec-federator.base64" .Values.mongo.password }}
  
  # Kafka credentials (base64 encoded)
  kafka-username: {{ include "mec-federator.base64" .Values.kafka.username }}
  kafka-password: {{ include "mec-federator.base64" .Values.kafka.password }}