services:
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME}-db
    ports:
      - "27017:27017"
    env_file:
      - ../../.env.a
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: