services:
  federator-oo:
    container_name: ${BASE_URL_OO}
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    environment:
      API_PORT: ${API_PORT_OO}
      BASE_URL: ${BASE_URL_OO}
      MONGO_HOST: ${MONGO_HOST_OO}
      MONGO_PORT: ${MONGO_PORT_OO}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID_OO}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET_OO}
      OAUTH2_TOKEN_ENDPOINT: ${OAUTH2_TOKEN_ENDPOINT}
    ports:
      - "8000:8000"
    depends_on:
      - mongo-oo
    networks:
      net-oo:
      net-federation:
        aliases:
          - ${BASE_URL_OO}

  mongo-oo:
    container_name: ${MONGO_HOST_OO}
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data-oo:/data/db
    networks:
      - net-oo

  mongo-express-oo:
    container_name: mongo-express-oo
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST_OO}:${MONGO_PORT_OO}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo-oo
    networks:
      - net-oo


  federator-po:
    container_name: ${BASE_URL_PO}
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    environment:
      API_PORT: ${API_PORT_PO}
      BASE_URL: ${BASE_URL_PO}
      MONGO_HOST: ${MONGO_HOST_PO}
      MONGO_PORT: ${MONGO_PORT_PO}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID_PO}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET_PO}
      OAUTH2_TOKEN_ENDPOINT: ${OAUTH2_TOKEN_ENDPOINT}
    ports:
      - "8001:8000"
    depends_on:
      - mongo-po
    networks:
      net-po:
      net-federation:
        aliases:
          - ${BASE_URL_PO}

  mongo-po:
    container_name: ${MONGO_HOST_PO}
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data-po:/data/db
    networks:
      - net-po

  mongo-express-po:
    container_name: mongo-express-po
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST_PO}:${MONGO_PORT_PO}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo-po
    networks:
      - net-po

volumes:
  mongo-data-oo:
    driver: local
  mongo-data-po:
    driver: local

networks:
  net-oo:
    driver: bridge
  net-po:
    driver: bridge
  net-federation:
    driver: bridge