services:
  federator-oo:
    container_name: ${BASE_URL_OO}
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    environment:
      OPERATOR_ID: ${OPERATOR_ID_OO}
      API_PORT: ${API_PORT_OO}
      BASE_URL: ${BASE_URL_OO}
      MONGO_HOST: ${MONGO_HOST_OO}
      MONGO_PORT: ${MONGO_PORT_OO}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_ORCHESTRATOR_DATABASE: ${MONGO_ORCHESTRATOR_DATABASE}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID_OO}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET_OO}
      OAUTH2_TOKEN_ENDPOINT: ${OAUTH2_TOKEN_ENDPOINT}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    ports:
      - "8000:8000"