apiVersion: v1
kind: Secret
metadata:
  name: federator-secrets
  namespace: osm-mec
  labels:
    app: federator
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  mongo-username: cm9vdA==
  mongo-password: cGFzcw==
  
  # Kafka credentials (base64 encoded)
  kafka-username: dXNlcjE=
  kafka-password: YlFTamlZb0wzMw==
  
  # OAuth2 credentials (base64 encoded)
  oauth2-client-id: b3BlcmF0b3ItYQ==
  oauth2-client-secret: RmtFWkU4dHdwNXNNbjNxY1Zxdm0zblpLenk5c0xBcjg=

---
# Template for creating secrets with kubectl (uncomment and modify as needed)
# 
# To create secrets manually with kubectl:
# kubectl create secret generic federator-secrets \
#   --from-literal=mongo-username=federator \
#   --from-literal=mongo-password-oo=federatorPassword \
#   --from-literal=kafka-username=federator \
#   --from-literal=kafka-password=federatorKafkaPassword \
#   --from-literal=oauth2-client-id=federator-client \
#   --from-literal=oauth2-client-secret=federator-client-secret \
#   --namespace=osm-mec

# To update existing secrets:
# kubectl patch secret federator-secrets \
#   --type='json' \
#   -p='[{"op": "replace", "path": "/data/mongo-password-oo", "value": "bmV3UGFzc3dvcmQ="}]' \
#   --namespace=osm-mec

# To view secret values (for debugging):
# kubectl get secret federator-secrets -o jsonpath="{.data.mongo-username}" --namespace=osm-mec | base64 --decode