apiVersion: apps/v1
kind: Deployment
metadata:
  name: mef
  namespace: osm-mec
  labels:
    app: mef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mef
  template:
    metadata:
      labels:
        app: mef
    spec:
      containers:
      - name: mef
        image: mankings/federator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8440
        env:
        - name: OPERATOR_ID
          value: "PARTNER"
        - name: API_PORT
          value: "8440"
        - name: BASE_URL
          value: "mef"
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: mongo-password
        - name: MONGO_DATABASE
          value: "federation"
        - name: MONGO_ORCHESTRATOR_DATABASE
          value: "db"
        - name: KAFKA_HOST
          value: "kafka-controller-headless.osm.svc.cluster.local"
        - name: KAFKA_PORT
          value: "9094"
        - name: KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: kafka-username
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: kafka-password
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: oauth2-client-id
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: federator-secrets
              key: oauth2-client-secret
        - name: OAUTH2_TOKEN_ENDPOINT
          value: "http://10.255.42.47:8080/realms/federation-realm/protocol/openid-connect/token"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8440
          initialDelaySeconds: 60
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8440
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mef-external
  namespace: osm-mec
spec:
  type: NodePort
  selector:
    app: mef
  ports:
  - port: 8440
    targetPort: 8440
    nodePort: 32440