basePath: /federation/v1
definitions:
  dto.AccessTokenRequestData:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
    type: object
  dto.GetArtefactResponse:
    properties:
      appProviderId:
        type: string
      artefactDescription:
        type: string
      artefactDescriptorFileFormat:
        $ref: '#/definitions/models.ArtefactFileFormat'
      artefactDescriptorType:
        $ref: '#/definitions/models.ArtefactDescriptorType'
      artefactId:
        type: string
      artefactName:
        type: string
      artefactVersionInfo:
        type: string
      artefactVirtType:
        $ref: '#/definitions/models.ArtefactVirtType'
      objectRepoLocation:
        $ref: '#/definitions/models.ObjectRepoLocation'
    type: object
  models.AccessToken:
    properties:
      accessToken:
        type: string
      expiresAt:
        type: string
    type: object
  models.ArtefactDescriptorType:
    enum:
    - HELM
    - TERRAFORM
    - ANSIBLE
    - SHELL
    - COMPONENTSPEC
    type: string
    x-enum-varnames:
    - HELM
    - TERRAFORM
    - ANSIBLE
    - SHELL
    - COMPONENTSPEC
  models.ArtefactFileFormat:
    enum:
    - ZIP
    - TAR
    - TEXT
    - TARGZ
    type: string
    x-enum-varnames:
    - ZIP
    - TAR
    - TEXT
    - TARGZ
  models.ArtefactVirtType:
    enum:
    - VM_TYPE
    - CONTAINER_TYPE
    type: string
    x-enum-varnames:
    - VM_TYPE
    - CONTAINER_TYPE
  models.FederationHealthInfo:
    properties:
      federationStartTime:
        type: string
      federationStatus:
        $ref: '#/definitions/models.State'
      numOfAcceptedZones:
        type: string
      numOfActiveAlarms:
        type: string
      numOfApplications:
        type: string
    type: object
  models.FederationMetaInfo:
    properties:
      allowedFixedNetworkIds:
        items:
          type: string
        type: array
      allowedMobileNetworkIds:
        $ref: '#/definitions/models.MobileNetworkIds'
      edgeDiscoveryServiceEndPoint:
        $ref: '#/definitions/models.ServiceEndpoint'
      lcmServiceEndPoint:
        $ref: '#/definitions/models.ServiceEndpoint'
      offeredAvailabilityZones:
        items:
          $ref: '#/definitions/models.ZoneDetails'
        type: array
      platformCaps:
        items:
          type: string
        type: array
    required:
    - platformCaps
    type: object
  models.FederationPatchParams:
    properties:
      addFixedNetworkIds:
        items:
          type: string
        type: array
      addMobileNetworkIds:
        $ref: '#/definitions/models.MobileNetworkIds'
      modificationDate:
        type: string
      objectType:
        description: Must be either "MOBILE_NETWORK_CODES" or "FIXED_NETWORK_CODES"
        type: string
      operationType:
        description: Must be either "ADD_CODES", "REMOVE_CODES" or "UPDATE_CODES"
        type: string
      removeFixedNetworkIds:
        items:
          type: string
        type: array
      removeMobileNetworkIds:
        $ref: '#/definitions/models.MobileNetworkIds'
    type: object
  models.FederationRequestData:
    properties:
      accessToken:
        $ref: '#/definitions/models.AccessToken'
      initialDate:
        description: Time zone info of the federation initiated by the originating
          OP
        type: string
      origOPCountryCode:
        type: string
      origOPFederationId:
        type: string
      origOPFixedNetworkCodes:
        items:
          type: string
        type: array
      origOPMobileNetworkCodes:
        $ref: '#/definitions/models.MobileNetworkIds'
      partnerStatusLink:
        type: string
    required:
    - accessToken
    - initialDate
    - partnerStatusLink
    type: object
  models.FederationResponseData:
    properties:
      edgeDiscoveryServiceEndPoint:
        $ref: '#/definitions/models.ServiceEndpoint'
      federationContextId:
        type: string
      federationExpiryDate:
        description: Date and Time zone info of the existing federation expiry
        type: string
      federationRenewalDate:
        description: Date and Time zone info of the existing federation renewal. Shall
          be less than federationExpiryDate
        type: string
      lcmServiceEndPoint:
        $ref: '#/definitions/models.ServiceEndpoint'
      offeredAvailabilityZones:
        description: List of zones, which the operator platform wishes to make available
          to developers/ISVs of requesting operator platform.
        items:
          $ref: '#/definitions/models.ZoneDetails'
        type: array
      partnerOPCountryCode:
        type: string
      partnerOPFederationId:
        type: string
      partnerOPFixedNetworkCodes:
        items:
          type: string
        type: array
      partnerOPMobileNetworkCodes:
        $ref: '#/definitions/models.MobileNetworkIds'
      platformCaps:
        items:
          type: string
        type: array
    required:
    - edgeDiscoveryServiceEndPoint
    - federationContextId
    - lcmServiceEndPoint
    - partnerOPCountryCode
    - platformCaps
    type: object
  models.InvalidParam:
    properties:
      param:
        type: string
      reason:
        type: string
    type: object
  models.MobileNetworkIds:
    properties:
      mcc:
        type: string
      mncs:
        items:
          type: string
        type: array
    type: object
  models.ObjectRepoLocation:
    properties:
      password:
        description: Password to access the repository
        type: string
      repoURL:
        type: string
      token:
        description: Authorization token to access the repository
        type: string
      userName:
        description: Username to access the repository
        type: string
    type: object
  models.ProblemDetails:
    properties:
      cause:
        description: Fixed string indicating cause of the issue
        type: string
      detail:
        description: Specific detail of the issue
        type: string
      invalidParams:
        items:
          $ref: '#/definitions/models.InvalidParam'
        type: array
      title:
        description: Summary of the problem
        type: string
    type: object
  models.ServiceEndpoint:
    properties:
      fqdn:
        type: string
      ipv4Addresses:
        items:
          type: string
        type: array
      ipv6Addresses:
        items:
          type: string
        type: array
      port:
        type: integer
    type: object
  models.State:
    properties:
      alarmState:
        description: Defines the alarm state during its life cycle (raised | updated
          | cleared).
        type: string
    type: object
  models.ZoneDetails:
    properties:
      geographyDetails:
        description: Details about cities or state covered by the edge. Details about
          the type of locality for eg rural, urban, industrial etc. This information
          is defined in human readable form.
        type: string
      geolocation:
        type: string
      zoneId:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the API documentation for the MEC Federator.
  title: MEC Federator API
  version: "1.0"
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      description: Issue an access token from Keycloak
      parameters:
      - description: Client ID and Client Secret
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AccessTokenRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Issue Access Token
      tags:
      - Authentication
  /ewbi/{federationContextId}/artefact:
    post:
      consumes:
      - multipart/form-data
      description: Receives an artefact from origin OP. Artefact is a zip file containing
        scripts and/or packaging files
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      - description: Artefact file
        in: formData
        name: artefactFile
        required: true
        type: file
      - description: Artefact ID
        in: formData
        name: artefactId
        required: true
        type: string
      - description: App Provider ID
        in: formData
        name: appProviderId
        required: true
        type: string
      - description: Artefact Name
        in: formData
        name: artefactName
        required: true
        type: string
      - description: Artefact Version Info
        in: formData
        name: artefactVersionInfo
        required: true
        type: string
      - description: Artefact Description
        in: formData
        name: artefactDescription
        required: true
        type: string
      - description: Artefact Virt Type
        in: formData
        name: artefactVirtType
        required: true
        type: string
      - description: Artefact Descriptor Type
        in: formData
        name: artefactDescriptorType
        required: true
        type: string
      - description: Artefact File Format
        in: formData
        name: artefactFileFormat
        required: true
        type: string
      - description: Artefact File Name
        in: formData
        name: artefactFileName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'status: Artefact onboarded successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Onboard an artefact
      tags:
      - EWBI - ArtefactManagement
  /ewbi/{federationContextId}/artefact/{artefactId}:
    delete:
      description: Delete an artefact by its id
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      - description: Artefact ID
        in: path
        name: artefactId
        required: true
        type: string
      responses:
        "200":
          description: 'status: Artefact deleted successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Delete an artefact
      tags:
      - EWBI - ArtefactManagement
  /ewbi/{federationContextId}/artefacts/{artefactId}:
    get:
      description: Get an artefact details by its id
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      - description: Artefact ID
        in: path
        name: artefactId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetArtefactResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Get an artefact
      tags:
      - EWBI - ArtefactManagement
  /ewbi/{federationContextId}/health:
    get:
      consumes:
      - application/json
      description: Checks the health status of the federation
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FederationHealthInfo'
        "400":
          description: Invalid federationContextId
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Get Local Federation Health Info
      tags:
      - EWBI - FederationManagement
  /ewbi/{federationContextId}/partner:
    delete:
      consumes:
      - application/json
      description: Removes a federation relationship by its federationContextId
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'status: Federation removed successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Remove Federation Relationship
      tags:
      - EWBI - FederationManagement
    get:
      consumes:
      - application/json
      description: Retrieves metadata information about a federation based on the
        federationContextId
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FederationMetaInfo'
        "400":
          description: Invalid Federation Context ID
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Get Federation Meta Info
      tags:
      - EWBI - FederationManagement
    patch:
      consumes:
      - application/json
      description: Updates a federation object with the given federationContextId
        and patch parameters
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      - description: Patch Parameters
        in: body
        name: patchParams
        required: true
        schema:
          $ref: '#/definitions/models.FederationPatchParams'
      produces:
      - application/json
      responses:
        "200":
          description: 'status: Federation updated successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request or federation not found
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Update Federation Details
      tags:
      - EWBI - FederationManagement
  /ewbi/{federationContextId}/renew:
    post:
      consumes:
      - application/json
      description: Renews the federation relationship with the given federationContextId
      parameters:
      - description: Federation Context ID
        in: path
        name: federationContextId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'federationContextId: id, federationRenewalDate: time, federationExpiryDate:
            time'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid federationContextId
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Renew Federation Relationship
      tags:
      - EWBI - FederationManagement
  /ewbi/fed-context-id:
    get:
      consumes:
      - application/json
      description: Retrieves the federationContextId using the accessToken
      parameters:
      - description: Access Token
        in: query
        name: accessToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'federationContextId: id'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: No Federation found with the given accessToken
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Get Federation Context Identifier
      tags:
      - EWBI - FederationManagement
  /ewbi/partner:
    post:
      consumes:
      - application/json
      description: Establishes a new federation relationship with another federator
        with the provided data
      parameters:
      - description: Federation Request Data
        in: body
        name: federationRequestData
        required: true
        schema:
          $ref: '#/definitions/models.FederationRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FederationResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ProblemDetails'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ProblemDetails'
      summary: Accept Federation Relationship
      tags:
      - EWBI - FederationManagement
swagger: "2.0"
